package property

const (
	Key = "Key"
	ID = "ID"
	RouterHash = "RouterHash"
	DomainID = "DomainID"
	RouterIP = "RouterIP"
	PeerHash = "PeerHash"
	PeerIP = "PeerIP"
	PeerASN = "PeerASN"
	Timestamp = "Timestamp"
	IGPRouterID = "IGPRouterID"
	ASN = "ASN"
	MTID = "MTID"
	AreaID = "AreaID"
	Protocol = "Protocol"
	ProtocolID = "ProtocolID"
	Name = "Name"
	IsPrepolicy = "IsPrepolicy"
	IsAdjRIBIn = "IsAdjRIBIn"
	Nexthop = "Nexthop"
	LocalLinkIP = "LocalLinkIP"
	RemoteLinkIP = "RemoteLinkIP"
	IGPMetric = "IGPMetric"
	RemoteNodeHash = "RemoteNodeHash"
	LocalNodeHash = "LocalNodeHash"
	RemoteIGPRouterID = "RemoteIGPRouterID"
	Prefix = "Prefix"
	PrefixLen = "PrefixLen"
	PrefixMetric = "PrefixMetric"
	LocalNodeASN = "LocalNodeASN"
	IGPFlags = "IGPFlags"
	SRv6SID = "SRv6SID"
	DataRate = "DataRate"
	PacketsSent = "PacketsSent"
	PacketsReceived = "PacketsReceived"
	State = "State"
	LastStateTransitionTime = "LastStateTransitionTime"
	From = "From"
	To = "To"
	Link = "Link"
)