name: JAGW Pipieline

on:
  workflow_dispatch:
    inputs:
      tag_name:   
        required: true
        type: string
      build_branch:
        description: "Build branch (dev | main)"
        required: true
        type: string
      release_or_dev:
        description: "Type (dev | release)"
        required: true
        type: string
      protorepo_jagw_go_ref:
        description: "Ref used by other go modules to import this version"
        required: true
        type: string

jobs:
  call-merge-to-main:
    if: github.event.inputs.release_or_dev == 'release'
    uses: jalapeno-api-gateway/jagw-core/.github/workflows/merge-to-main.yml@dev
  call-create-tag:
    needs: [call-merge-to-main]
    uses: jalapeno-api-gateway/jagw-core/.github/workflows/create-tag.yml@dev   
    if: |
      always() &&
      (needs.call-merge-to-main.result == 'success' || needs.call-merge-to-main.result == 'skipped')
  call-create-release:
    needs: [call-merge-to-main, call-create-tag]
    uses: jalapeno-api-gateway/jagw-core/.github/workflows/create-release.yml@dev
  call-trigger-remote-repo:
    needs: [call-create-tag]
    uses: jalapeno-api-gateway/jagw-core/.github/workflows/trigger-remote-repo.yml@dev
    if: |
      always() &&
      (needs.call-merge-to-main.result == 'success' || needs.call-merge-to-main.result == 'skipped') &&
      needs.call-create-tag.result == 'success'
    with:
      workflow_file: jagw-pipeline.yml
      protorepo_jagw_go_ref: ${{ github.event.inputs.protorepo_jagw_go_commit_sha }}
      jagw_core_ref: ${{ needs.call-create-tag.outputs.jagw_core_ref }}
    secrets:
      pat_full_repo_access: ${{ secrets.PAT_FULL_REPO_ACCESS }}
